name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-20.04
 
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Run hadolint
      run: make lint
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag phantomjs-python:$(date +%s)
